##端口号
server:
  port: 8080
dubbo:
  application:
    name: dubbo-consumber
  registry:
    address: zookeeper://192.168.0.111:2181
  protocol:
    name: dubbo
    port: 20081
  scan:
    base-packages: com.xinyue.dubbo.provider.service
  metadata-report:
    address: zookeeper://192.168.0.111:2181
  consumer:
    group: blog