
server:
  port: 8003

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xinyue.model

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xinyue
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xinyue
    password: 123456
  application:
    name: iboot-provider


eureka:
  client:
    service-url:
      defaultZone: http://eureka000:7001/eureka/
  instance:
    instance-id: iboot-provider8003
    prefer-ip-address: true

info:
  app.name: iboot-provider002
  company.name: com.xinyue
  build.artifactId: @project.version@
  build.version: @project.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"