server:
  port: 8001

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xinyue.model

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xinyue
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xinyue
    password: 123456