server:
  port: 9002


eureka:
  client:
    service-url:
      defaultZone: http://eureka000:7001/eureka/
  instance:
    instance-id: iboot-config
    prefer-ip-address: true

spring:
  application:
    name: iboot-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sangzhenya/code-samples.git
