server:
  port: 8005
spring:
  application:
    name: iboot-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka000:7001/eureka/
  instance:
    instance-id: iboot-config-client
    prefer-ip-address: true

---
server:
  port: 8005
spring:
  profiles: dev
