server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: iboot-consumer8001
    prefer-ip-address: true

info:
  app.name: iboot-consumer
  company.name: com.xinyue
  build.artifactId: @project.version@
  build.version: @project.version@
spring:
  application:
    name: iboot-consumer
