spring:
  datasource:
    username: xinyue
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xinyue?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  session:
    store-type: none