server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://eureka000:7001/eureka/
    register-with-eureka: false
  instance:
    instance-id: iboot-consumer-hystrix
    prefer-ip-address: true

info:
  app.name: iboot-consumer-hystrix
  company.name: com.xinyue
  build.artifactId: @project.version@
  build.version: @project.version@
spring:
  application:
    name: iboot-consumer
feign:
  hystrix:
    enabled: true
