server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://eureka000:7001/eureka/
    register-with-eureka: false
  instance:
    instance-id: iboot-consumer8080
    prefer-ip-address: true

info:
  app.name: iboot-consumer
  company.name: com.xinyue
  build.artifactId: @project.version@
  build.version: @project.version@
spring:
  application:
    name: iboot-consumer
